### ISSUE TITLE
Additional addons for revisions?

### ISSUE THREAD

**Issue by srvance** [kpfefferle/ember-cli-deploy-aws-pack#9]
What's the interest in adding s3-index, revision-data, and display-revisions to get a more developed version and activation strategy? It wouldn't achieve the full lightning preview capability, but it would support rapid rollback.

I'm playing with it myself, but wanted to hear your thoughts before doing a PR.

**Comment by kpfefferle** [comment]
@srvance When creating this plugin pack, I intentionally avoided the added complexity of including and configuring the s3-index plugin because I did not need it in order to achieve my own deployment setup. If an AWS plugin pack that includes index revisioning is something you'd be interested in sharing with the community, perhaps a fork of this plugin pack with the added plugins and config blueprint would accomplish this goal?

**Comment by srvance** [comment]
Thanks, Kevin. I'll consider that avenue.
